name: fieldnote
description: Secure, local-first audio journaling for professionals.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.9.1
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  record: ^5.0.0
  speech_to_text: ^6.3.0

dev_dependencies:
  # Code Generation & Build Tools
  build_runner: ^2.4.6 # Code generation tool
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1 # Isar database code generator

flutter:
  uses-material-design: true
