import 'package:isar/isar.dart';

part 'note.g.dart'; // This file will be generated by build_runner

@collection
class Note {
  Id id = Isar.autoIncrement;

  late String audioFilePath;

  // Transcription will be added in the next task
  String transcription = '';

  late DateTime createdAt;

  late int durationInSeconds;
}
